### ISSUE TITLE
Quad.php: align naming of getGraphIri and withGraphIri

### ISSUE THREAD

**Issue by k00ni** [sweetrdf/rdfInterface#13]
`Quad.php` has functions `getGraphIri` and `withGraphIri` whose name is not in line with other functions (like `getSubject`), because `Iri` in the name lets one assume it is a string and not an object. 

I propose to change it to `getGraph` and `withGraph`.

**Comment by zozlak** [comment]
I'm fine with that change. Would you prepare a PR?

**Comment by k00ni** [comment]
Sure, no problem.

**Comment by zozlak** [comment]
Solved by 554c7dc9f74246d751957b7998d8b15a55c85bdc
