### ISSUE TITLE
Is Term->getType needed?

### ISSUE THREAD

**Issue by zozlak** [sweetrdf/rdfInterface#16]
`Term::getType()` has been just copy-pasted from RDF/JS but when I think about it it's needed in JS because of its (creepy) object model and in PHP we can just use `$object instanceof SpecificTermClass`. Which makes the `Term::getType()` just an unneeded boilerplate.

**Comment by zozlak** [comment]
What do you think @k00ni ?

**Comment by k00ni** [comment]
Sounds reasonable and makes code more clean.

**Comment by k00ni** [comment]
Did 3eafabc solve the issue?

**Comment by zozlak** [comment]
Yes.
