### ISSUE TITLE
Reduce copyright info in each file header and just reference LICENSE file

### ISSUE THREAD

**Issue by k00ni** [sweetrdf/rdfInterface#3]
Instead of that long MIT license text in each file header, we should reduce that to something like:

```
/*
 * This file is part of the rdfinterface package and licensed under the terms of the MIT-license.
 *
 * (c) XXX <YYY>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */
```

I like the style of the Symfony project, for instance: https://github.com/symfony/symfony/blob/5.x/src/Symfony/Component/Form/AbstractExtension.php#L3-L10

**Comment by zozlak** [comment]
> we should reduce that to something like:

"Should" is a strong word. "May" is a better one.

Anyway, this header is automatically generated by the IDE so I don't see any benefit from making it shorter or longer. It doesn't make anything easier, e.g. if we decide to change a license we anyway must find and replace in all files (as even the short header you propose contains the license name). And until changing to short ones provides no benefit and costs some (even short) time, I don't see a reason to introduce the change.

Could you provide any practical reason for such a change?

**Comment by k00ni** [comment]
> Anyway, this header is automatically generated by the IDE so I don't see any benefit from making it shorter or longer.

Ah OK. If your IDE handles it for you, its fine to leave it as it is. I use Visual Studio Code and add/adapt these manually, so I thought you do it the same way.

**Comment by zozlak** [comment]
Looks like there is a plugin for the VSC for that - see https://stackoverflow.com/questions/38823319/automatically-add-copyright-banner-in-vs-code

**Comment by k00ni** [comment]
I run PHP-CS-Fixer from time to time to not only keep my coding styles but also keep file headers up to date.
