### ISSUE TITLE
Provide standard classes for each interface?

### ISSUE THREAD

**Issue by k00ni** [sweetrdf/rdfInterface#4]
For each interface we should provide a class which implements it. That should help users because they don't have to implement it by themselves. This way we can also provide some kind of a standard reference.

We could use `Impl` as a suffix for each class, like `Literal` (interface) and `LiteralImpl` (class). The class **shouldn't** be `final`, but its properties are all `private`.

What do you think?

**Comment by zozlak** [comment]
First, even if I would prepare a reference implementation, I would definitely do it in a separate composer library and use separate namespace (which makes the naming convention a matter of taste). Just like quickRdf does. Look at the PSR interfaces - they always come alone and implementations come separately and that's for a reason.

Second, it's a good question to which extent it makes sense to provide a reference implementation. I have two concerns here:

* To which extend it's useful for preparing your own implementation. By looking at my quickRdf I would say it won't be helpful at all.
* I'm generally against extending classes developed by someone else. This leads to problems with code maintenance as when you extend class, you (sooner or later) depend on the parent's class internal structure but if your parent's class is developed by someone else you have no guarantee of stability of its internal structure. The right way here is to depend on public interfaces but in such a case there is no added value from extending particular implementation class. Moreover, depending on the public interface doesn't bond your implementation to particular interface implementation (which also brings some goodies when it comes for testing, e.g. much easier stubbing) but it also means you don't care if a reference implementation of a given interface exists. You are just fine if at least one implementation exists.

**Comment by k00ni** [comment]
The reason for a reference implementation is that it helps other libraries to adopt and use our code / interfaces. It also remove the task of creating classes for each interface one wanna use. Using final classes is OK with me. People might not be familiar with RDF internals, but they wanna work with RDF on high level, for instance parse and work with RDFa from a website.

Is the purpose of your `quickRdf` repository to act as a reference implementation? If so, is it OK with you to refine it? If not, its fine with me, I would make a new repository on my own then.

**Comment by zozlak** [comment]
> Is the purpose of your quickRdf repository to act as a reference implementation?

Yes, it is (more in the "first available implementation" sense than "the best or most clear (or superior in any other way) available implementation" sense but yes). And that's how it's stated in this repository README - https://github.com/sweetrdf/rdfInterface/#reference-implementation .

> If so, is it OK with you to refine it?

What do you mean by refining?

> Using final classes is OK with me.

I'm confused here. Where we should/shouldn't use final classes?
While I fully agree with "final classes proponents" that extending by class inheritance should be limited (and avoided at all when it comes to foreign code; good summary of reasons is stated [here](https://ocramius.github.io/blog/when-to-declare-classes-final/)) I also think it's to large extent a matter of taste and I'm not sure I would like to enforce it on others here. I mean if they wanna extend my classes and they do it on their own responsibility in their own repositories, I don't care and I would just allow it. I would start using `final` if I was supervising a group of programmers and I would like to enforce (in my opinion) good programming practices but (at least for now ;) ) it's not a case here.

**Comment by k00ni** [comment]
I just had other impressions where you wanna go with your libraries (based on your thoughts in our Skype chats). Its more clear to me now and are you are right with keeping it open and allow foreigners to adapt/extend code without enforcing to much.
