### ISSUE TITLE
American or British English?

### ISSUE THREAD

**Issue by k00ni** [sweetrdf/rdfInterface#6]
Its a minor thing, but do we prefer American or British English?

**Example:** In class `Serializer` is a method called `serialiseStream`. People might wonder why they get errors if they use American English, but some terms are in British English.

**Comment by zozlak** [comment]
You are right, it should be used consistently. Do you have any preferences? (I don't)

**Comment by k00ni** [comment]
American English is common, so we should use that.

**Comment by zozlak** [comment]
Applied in 9bc4fe759b3b7e9d6386192710e46fb5716e2d47 (and pushed down to quidRdf, quickRdfIo and rdfHelpers)
